title: Deep Neural Network Policies
  
description: Study of Training Deep Neural Network Policies for Autonomous Navigation.
show_downloads: false
google_analytics: UA-109679980-2

theme: jekyll-theme-slate
